package top.yunov.neteasy.ui.theme

import androidx.compose.ui.graphics.Color

// —— MD3 Expressive 配色：网易云品牌红 + 暖色容器体系 ——

// Light
val LightPrimary = Color(0xFFD92D1F)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDAD3)
val LightOnPrimaryContainer = Color(0xFF3B0700)
val LightSecondary = Color(0xFF77574E)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDAD0)
val LightOnSecondaryContainer = Color(0xFF2C150F)
val LightTertiary = Color(0xFF6E5F00)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFFAE36B)
val LightOnTertiaryContainer = Color(0xFF221B00)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFF8F6)
val LightOnBackground = Color(0xFF231917)
val LightSurface = Color(0xFFFFF8F6)
val LightOnSurface = Color(0xFF231917)
val LightSurfaceVariant = Color(0xFFF5DEDA)
val LightOnSurfaceVariant = Color(0xFF53433F)
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFFFF1ED)
val LightSurfaceContainer = Color(0xFFFBE9E5)
val LightSurfaceContainerHigh = Color(0xFFF5E3DF)
val LightSurfaceContainerHighest = Color(0xFFEFDDD9)
val LightOutline = Color(0xFF85736E)
val LightOutlineVariant = Color(0xFFD8C2BD)

// Dark
val DarkPrimary = Color(0xFFFFB4A8)
val DarkOnPrimary = Color(0xFF5F1508)
val DarkPrimaryContainer = Color(0xFF8A2414)
val DarkOnPrimaryContainer = Color(0xFFFFDAD3)
val DarkSecondary = Color(0xFFE7BDB2)
val DarkOnSecondary = Color(0xFF442A23)
val DarkSecondaryContainer = Color(0xFF5D4038)
val DarkOnSecondaryContainer = Color(0xFFFFDAD0)
val DarkTertiary = Color(0xFFDDC747)
val DarkOnTertiary = Color(0xFF3A2F00)
val DarkTertiaryContainer = Color(0xFF534600)
val DarkOnTertiaryContainer = Color(0xFFFAE36B)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1110)
val DarkOnBackground = Color(0xFFF0DED9)
val DarkSurface = Color(0xFF1A1110)
val DarkOnSurface = Color(0xFFF0DED9)
val DarkSurfaceVariant = Color(0xFF53433F)
val DarkOnSurfaceVariant = Color(0xFFD8C2BD)
val DarkSurfaceContainerLowest = Color(0xFF140B0A)
val DarkSurfaceContainerLow = Color(0xFF221917)
val DarkSurfaceContainer = Color(0xFF271D1B)
val DarkSurfaceContainerHigh = Color(0xFF312725)
val DarkSurfaceContainerHighest = Color(0xFF3D322F)
val DarkOutline = Color(0xFFA08C87)
val DarkOutlineVariant = Color(0xFF53433F)
